### ISSUE TITLE
手机端按钮链接太多问题

### ISSUE THREAD

**Issue by ldxw** [noisky/Homepage#3]
`<li class="navigation_item">`这玩意搞太多手机端下拉`` 底部 Copyright 这个会遮住 按不了。。

**Comment by noisky** [comment]
已更新，现在手机端点开导航栏会隐藏底部 footer 栏，并且导航项超出屏幕时可以进行滚动，你可以试一下~

**Comment by ldxw** [comment]
电脑版你会这样吗？
![电脑版_2020-02-28_12-16-49.png](https://i.loli.net/2020/02/28/XGA43kxBiu8DKp2.png)

**Comment by noisky** [comment]
我修改下电脑端的显示，现在导航数目应该不会影响到底部的 footer 了，如果还是有问题可以提供下测试链接，方便定位问题所在

**Comment by ldxw** [comment]
暂时没有了，
